[package]
name = "roman_to_integer"
version = "0.1.0"
authors = ["Coenraad Human <coen.human@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
